version: '3'

services:
  app:
    build:
      context: app
    image: lucassantos/node:latest
    entrypoint: dockerize --wait tcp://db:3306 -timeout 30s npm start
    networks:
      - docker-challenge-network
    tty: true
    container_name: app
    volumes:
      - ./app:/usr/src/app
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./db/.docker/database:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=challengedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_USER=root
    networks: 
      - docker-challenge-network
  
  nginx:
    build: 
      context: nginx
    image: lucassantos/nginx
    container_name: nginx
    tty: true
    networks:
      - docker-challenge-network
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 8080:80
    depends_on:
      - app

networks:
  docker-challenge-network:
    driver: bridge
